### ISSUE TITLE
Suggestions for hardware implementation

### ISSUE THREAD

**Issue by ng435** [vg249/ECE5775_HybridImageProject#2]
Hi Gai Liu,

We are working on the Hybrid imaging project which is our course project (ECE 5775). This involves performing FFT and FFT shift on the image. 
We have implemented this code in C++ and trying to implement the same on hardware. If you could spare some time tomorrow, we would like to meet you and discuss about the implementation. Please let us know a convenient time (we are free whole day except from 2.30 to 4.00).

Thank you.

**Comment by gl387** [comment]
Could you let me know which files are relavent to your design? Do you have your own fft module, or are you using the library fft from Cimg? I need to take a close look at what you have right now before making suggestions.

**Comment by ng435** [comment]
Please find our code at -
ECE5775_HybridImageProject/CImg/CimgExample.cpp

We are using the fft module from Cimg and for hardware implementation, we would like to use the fft module available in vivado_hls - hls::fft

**Comment by gl387** [comment]
I see. Please first replace get_FFT function and cimglist_apply(*,shift) with vivado_hls supported functions. Then create a top-level function for your design with kernel functions (fft, ifft, shift and GaussFilter) inside, and extract the other parts in the main fucntion (reading & writing images) to a separate test file (your_design_name_test.cpp). You can refer to the cordic design and digitrec design for how to arrange the code. After that I can generate a tcl script for you to synthesize your design.

**Comment by gl387** [comment]
I have committed a reference FFT design from Xilinx under fft_single folder. you can do "vivado_hls run_hls.tcl" in that folder to synthesize the design. You'll then need to modify the configurations of the FFT to suit your own design. Please checkout the code as well as the following document on how to configure the FFT module:
http://www.xilinx.com/support/documentation/sw_manuals/xilinx2014_2/ug902-vivado-high-level-synthesis.pdf (starting from page 294).

**Comment by vg249** [comment]
Thank you very much. We are using fft_ifft example  module to test the Image data. We replaced the Testing data with image data read from CImg, and ran fft_ifft module. The output values are different from the output we got from CImg FFT. We did not understand FFT configuration parameters like "Transform Size(NFFT)" and "Scaling Schedule". We will try with fft_single now and will let you know the results.

**Comment by vg249** [comment]
Hi Gai,
We found that fft_single is also same as that of the fft_ifft as far as FFT function is considered. We modified the test bench of the fft_ifft, "fft_tb.cpp" to read image using CImg library. When we run it we are getting undefined reference error. We made sure the respective headers are added in the test bench file. The error is arising during co simulation. Do we need to add or register the CImg library, so that Vivado CSim can access it. (Also added the required CFlags in the .tcl file) We have pushed the code in the following path,

/FFT/fft_ifft/fft_tb.cpp

**Comment by zhangzhiru** [comment]
I dont see FFT/fft_ifft/fft_tb.cpp

**Comment by zhangzhiru** [comment]
Also, it's not clear how to run your C simulation with CImg. There is no Makefile or useful README. Please spend some effort cleanup your code and directories. There are multiple folders scattered around. Make sure you don't push in any automatically generated files.

**Comment by ng435** [comment]
Hi Professor,

Sometimes it doesn't show up even with refresh. Can you please try using
this link instead -

https://github.com/vg249/ECE5775_HybridImageProject/blob/master/FFT/fft_ifft/fft_tb.cpp

**Comment by zhangzhiru** [comment]
I still don't know how to run your original CImg design. Anyways, all you need is to specify the right LDFLAGS for linking the CImg library. Please do "git pull" and complete the -ldflags in the csim command in run_hls.tcl. 

#csim_design -ldflags ""

**Comment by vg249** [comment]
Thank you professor, CImg is loading after adding ldfalgs. getting segmentation faults when reading the image. We will let you know once we debugged.

**Comment by ng435** [comment]
Hi Professor,

We have cleaned up the unwanted directories and included the README.txt file which explains how to compile the original Cimg C++ code. We will also convert this to a make file so that it would be easy for compiling and cleaning up.

**Comment by vg249** [comment]
Roadblocks with segmenation faults, sqrt, log and Normalization compilation errors were resolved.
Not sure whether the Normalization function created was correct.(Reference: https://en.wikipedia.org/wiki/Normalization_(image_processing)). We will review it once more.

Tried FFT and Inverse FFT of the Image to get the original image. Failure, as the magnitude of the result is not matching with the baseline design's magnitude values.

++Gai - Help on understanding the Configuration parameters of xilinx FFT module (especially Scaling Schedule) would be greatly appreciated. 

Code Path : /FFT/fft_ifft/fft_tb.cpp
Note: Codes are commented in baseline /CImg/Hybrid_image.cpp for the purpose of comparing the values.

**Comment by gl387** [comment]
The document I sent out has summary on the paramters and configurations of the FFT (http://www.xilinx.com/support/documentation/sw_manuals/xilinx2014_2/ug902-vivado-high-level-synthesis.pdf) (starting from page 296). You can also checkout the fft header file to learn the implementation details of the features. The header file can be found here on amdpool:
/opt/xilinx/Vivado_HLS/2014.2/include/hls_fft.h

You can search for the corresponding functions to learn more about how they're implemented.

**Comment by vg249** [comment]
Thank you Gai.
Doing Trail and Error method to come up with correct FFT value.
We will let you know once, we found something. Thank you again.

**Comment by vg249** [comment]
We completed the top level function and test bench implementation in amdpool. Also we moved FFT, FFTshift, Gauss filter and normalization functions to top level module. The updated working scripts are at -
https://github.com/vg249/ECE5775_HybridImageProject/tree/master/FFT/fft_single

Please find the result image that we obtained -
![image](https://cloud.githubusercontent.com/assets/14043628/11677319/56401178-9e0a-11e5-9adc-a84aab381057.png)

Next step is implementing the same on FPGA. To setup the FPGA interface, can we follow the same method as example design of FFT or do we need to follow the same procedure that we did on last assignment? In the FFT example design, pragmas were used to setup the interfaces. Thanks for your time.

**Comment by ng435** [comment]
Hi Professor/Gai,

We are streaming the image data similar to the digitrec assignment and it was successfully synthesized as well. The updated code is on the github at -
https://github.com/vg249/ECE5775_HybridImageProject/tree/master/hybrid_image/amdpool

We are currently trying to generate the bitstream and its giving out error saying -

terminate called after throwing an instance of 'HXMLException'
  what():  ERROR: [Runs 36-300] XML parser encountered a problem in /home/student/ng435/ECE5775_HybridImageProject/hybrid_image/amdpool/zedboard_project/xillybus/vivado/xillydemo.runs/.jobs/vrs_config_1.xml at line 1 : Unexpected end of message

/research/brg/install/bare-pkgs/x86_64-centos6/pkgs/xilinx-vivado-2015.2/Vivado/2015.2/bin/loader: line 157:  2412 Aborted                 "$RDI_PROG" "$@"

Can you please let us know how to go about this error?

**Comment by vg249** [comment]
As a follow up to Nagaraj's doubt, 
We designed the dut with two input ports and one output port.
Could you please confirm whether that is correct or is there any constraints in number of ports we can use for the design?

**Comment by vg249** [comment]
Ok......Port errors resolved...now a new problem !!!

ERROR: [Synth 8-3202] design needs 2816 RAMB exceeds device capacity of 280
ERROR: design has too many RAMB cells and cannot be implemented on the device.
8856 Infos, 197 Warnings, 3 Critical Warnings and 2 Errors encountered.
ERROR: [Common 17-69] Command failed: Vivado Synthesis failed

Planning to reduce the size of the image. Alternative ideas are welcome.
Pushing the code...
https://github.com/vg249/ECE5775_HybridImageProject/tree/master/hybrid_image/amdpool

**Comment by vg249** [comment]
While generating bitstream, getting Timing Constraints not met error.

INFO: [Timing 38-91] UpdateTimingParams: Speed grade: -1, Delay Type: min_max.
INFO: [Timing 38-191] Multithreading enabled for timing update using a maximum of 8 CPUs
report_timing_summary: Time (s): cpu = 00:01:21 ; elapsed = 00:00:19 . Memory (MB): peak = 2624.953 ; gain = 0.000 ; free physical = 3544 ; free virtual = 15106
ERROR: [showstopper-0] Timing constraints weren't met. Please check your design. See Timing Summary Report.
ERROR: [runtcl-1] ERROR: [Common 17-39] 'send_msg_id' failed due to earlier errors.
ERROR: [Common 17-39] 'send_msg_id' failed due to earlier errors.

Pushed the code to the same folder as above.

**Comment by zhangzhiru** [comment]
Can we use "float" instead of "double"?  
We don't need this much of precision, and making this change should dramatically reduce area and help close timing.

**Comment by ng435** [comment]
Hi Professor,

We are trying to modify it to float but on the other option, we observed that the WNS of the timing is -16ns so we wanted to increase the time period of the clock to 20ns and run. 

Can you please tell us how to modify that while generating the bitstream?  Because I am still seeing the clock period its analyzing is 10ns as -
create_clock -name gclk -period 10 [get_ports "clk_100"]

**Comment by zhangzhiru** [comment]
We need to meet 100MHz. Otherwise, the design may not function on FPGA, due to specific setup we are using for assignment 4. Please change to float first. Then we can consider further reducing the complexity of the hardware part by only moving part of the design to FPGA (say, FFT).

**Comment by vg249** [comment]
Yes professor. We got 16ns after changing to float. As per your advise, We will check the time taken for individual module and move some of them back to software.

**Comment by ng435** [comment]
Hi Professor/ Gai,

We are trying to login to zedboard using ssh ng435@zhang-zedboard-01.ece.cornell.edu but we were not able to login and the connection is getting timed out. We tried the same procedure as we did for the assignment. Can you please tell me if we need to modify anything or source any file? Thanks for your help.

**Comment by zhangzhiru** [comment]
Have you tried zedboard-02 and 03?

**Comment by ng435** [comment]
Thanks Professor with zedboard 03 it worked fine. 

We are getting error when we run the FPGA  implementation on zedboard as -
virtual memory exhausted: Cannot allocate memory

We didn't see this error while generating the bit stream. Can you please tell us how do we go about this?

**Comment by zhangzhiru** [comment]
Are you able to run the pure software simulation on ARM?

**Comment by ng435** [comment]
yes professor, we are able to.

**Comment by zhangzhiru** [comment]
Are you allocating a big array for the ARM+FPGA version? Any major differences from the pure software version. Perhaps you can try zedboard-04 as well? 

It's hard for me to tell what's the issue, and unfortunately I have to go offline very soon. Perhaps you can ping Gai to see if he is available to help.

**Comment by gl387** [comment]
Are all the files pushed on Github? How should I reproduce the error?

**Comment by ng435** [comment]
Thanks professor. We ll ping Gai

**Comment by ng435** [comment]
@Gai...we ll push the code soon...

**Comment by ng435** [comment]
Hi Gai,

Please follow the commands to reproduce -

% mkdir test
% cd test
% git clone git@github.com:vg249/ECE5775_HybridImageProject
% cd ECE5775_HybridImageProject/hybrid_image/zedboard
% scp xillydemo.bit <user>@zhang-zedboard-0x.ece.cornell.edu:~
% cd ..
% scp -r zedboard <user>@zhang-zedboard-0x.ece.cornell.edu:~
% ssh <user>@zhang-zedboard-0x.ece.cornell.edu

After login into zedboard-
@localhost: cd zedboard
@localhost: make fpga

Please let us know if you find any errors while following this procedure. Thanks

**Comment by gl387** [comment]
Can you try again? I added a swap file and I don't have the "Cannot allocate memory" problem anymore.

**Comment by zhangzhiru** [comment]
@ng435 Is the problem eventually solved? If so, please close this issue.

**Comment by ng435** [comment]
Yes professor the virtual memory problem was solved but it was still
failing with the error -lx11 library not found, so Gai tried adding it to
the zedboard. But we still see the error. So we are trying to fix that.

**Comment by ng435** [comment]
Hi Professor/ Gai,

Thanks for all the help. Professor, I am closing this issue as Gai was able to help us in running the code on the zedboard by including all the libraries required.

**Comment by gl387** [comment]
We can actually close timing by setting the timing constraint to 5ns in Vivado_HLS. The Vivado RTL flow still uses 10ns constraint. This way I have 1.606ns positive slack.

**Comment by ng435** [comment]
Yes we tried with 5ns and it generated the bitstream with this setting.
Thanks Gai and Professor for the suggestions.
